import { Box } from 'ui-kit';
import { Layout } from 'components';

import { htmlToReactParser } from 'utils';

const policy = `<div><h3>Introduction to Our Privacy Policy
</h3><div>There are many different ways you can interact online with Christ Fellowship Church, Inc. and our affiliated legal entities (“Christ Fellowship“, “we“, “us” or “our“), like watching or reading content, being generous through giving, connecting with other people, or taking your next step.  We appreciate your interest in our church and respect your privacy as you interact with us online. Or on App
</div><div>This Privacy Policy describes how we may treat your information that we have gathered from our websites, including christfellowship.church, gochristfellowship.com, christfellowshipcreative.com, ourheartforthehouse.com, cfspiritualgifts.com, churchunitedfl.com, viveconf.com, christfellowshipconference.com, hopehouseflorida.com, christfellowshipworship.shop, christfellowshipworship.com, cfbelleglade.com, cfseu.com, cfkaleo.com, realityrehab.tv, soallmayknow.com, live.gochristfellowship.com, rock.gocf.org, restorecoffeeroasters.com; (collectively, our “Websites”), and the services and tools related to the Websites (including, but not limited to, mobile and other software applications downloaded from the Websites or obtained elsewhere) (collectively, the “Services”).  Please read this Privacy Policy carefully.  We did our best to keep the document simple, but if you have any questions regarding this Privacy Policy or the use of your data, please contact our Marketing Team. By accessing or using any of our Websites, Mobile Application or Services you agree to this Privacy Policy and our Terms of Use.
</div><div>NOTICE REGARDING DISPUTE RESOLUTION: In keeping with 1 Corinthians 6:1-8, all disputes or claims arising under this Privacy Policy, or relating in any way to your use of the Websites, Mobile App or Services, will be resolved by mediation, and, if not resolved by mediation, then by final and binding arbitration as provided for in Section 9 of our Terms of Use. Unless you opt out, you will only be able to pursue claims against Christ Fellowship Church, Inc. on an individual basis, not as part of any class or representative action or proceeding, and you will only be permitted to seek relief (including monetary, injunctive, and declaratory relief) on an individual basis.
</div><br><div>
</div><h3>Application of Our Privacy Policy
</h3><div>This Privacy Policy applies only to information collected by the Websites, Mobile App or Services. It does not apply to information either collected by us offline or collected by unaffiliated Websites, Mobile App or Services.  Furthermore, this Privacy Policy governs only information provided to and communicated from the Websites, Mobile App or Services directly and does not govern any other information or communications that may reference this Website, the Services or Christ Fellowship.
</div><div>If you click “like” or make a comment on or about our Websites, Mobile App or Services using Facebook, Instagram, Twitter, Pinterest, or other social media plugins, your activity may be published on Facebook, Instagram, Twitter, Pinterest, or other social media website(s), and be shown to other individuals who visit our Websites.  We encourage you to read each social media site’s respective privacy policy for more information.
</div><br><div>
</div><h3>Information We Collect About You and How We Collect It
</h3><div>We collect several types of information from and about the users of our Websites and Services, including information by which you may be personally identified, such as your name, postal address, e-mail address, telephone number, credit card information or any other information the Websites, Mobile App and Services collect that is defined as personal or personally identifiable information under an applicable law or that may otherwise be used to identify you (collectively, your “Personal Information”).  We also may automatically collect information as you navigate the Websites and use the Services, including information such as usage details, IP addresses and information collected through the use of “cookies.”
</div><div>Information You Provide to Us.  When you visit our Websites and Services, you may be asked to provide Personal Information to register for a Christ Fellowship Account or participate in other activities.  If you communicate with us by e-mail, post messages to any of our chat groups, blogs, or otherwise complete online forms or surveys, any information provided in such communications may be collected as Personal Information.  You also may publish or display information on public areas of the Websites, Services or related websites (“User Contributions”). Your User Contributions are posted and transmitted to others at your own risk.  No security measures are perfect, and we cannot control the actions of third parties with whom you share your User Contributions.  Therefore, we cannot and do not guarantee that your User Contributions will not be viewed by unauthorized persons.  We will only collect User Contributions and Personal Information which you voluntarily provide.  When you submit such User Contributions and Personal Information on our Websites and Services, you are giving your consent to the collection, use and disclosure of such information as set forth in this Privacy Policy.
</div><div>Credit Card Information.  Unless you are a Christ Fellowship Account holder and have opted in for us to store your credit card information, we will not store full credit card numbers, credit expiration dates or CVV numbers on our servers.  If you have not authorized us to store your credit card information, this info is sent directly to our processor and then the bank to complete the transaction.  We do store other card information such as name, address, phone number and email address in order to assist with your transactions.
</div><div>Information We Collect Automatically.  When you download, access or use the Websites, Mobile App or Services, they may automatically collect:  (i) usage details (including traffic data, location data, communication data and the resources you access and use through the Websites and Services); (ii) device information (including IP address, operating system, browser type, hardware ID, mobile network information and the device’s telephone number); (iii) stored information (including metadata and other information associated with the files stored on your device, such as photographs, audio and video clips, personal contacts and address book information); and (iv) location information (including real-time information about the location of your device).  We also may use automatic data collection technology to gather information about your activities over time and across third-party websites, apps or other online services (behavioral tracking). If you do not want us to collect any of the information outlined in this section, you may opt out at any time by contacting our Marketing Team. Please note that we will not access any of your stored information (including photos, personal contacts and address book information), as well as your location information, unless you have specifically opted-in to allowing us such access.
</div><div>The collection of information helps us to make your online experience with us more enjoyable, by allowing us to tailor your online experiences to you while using our Websites and Services.
</div><div>Do Not Track Signals.  Do Not Track signals are signals sent through a browser informing us that you do not want to be tracked.  Because these signals are not universally supported by all browsers and sites, we do not currently assign any meaning to potential Do Not Track signals.
</div><div>Information Collection Technologies.  The technologies we use for automatic information collection may include cookies (including mobile cookies) or web beacons.  Cookies are small files sent to and stored on the computer or device you use to access or use our Websites, Mobile App or Services.  Cookies may be used to monitor use of our Websites, Mobile App or Services, customize content specific to your interests, ensure that you do not see the same information repeatedly, and store your user name and password (using encryption technology) so you do not have to re-enter it each time you access or use the Websites, Mobile App or Services. It may be possible to refuse to accept cookies by activating the appropriate setting on your computer or device.  However, if you select this setting you may be unable to access certain portions of our Websites, Mobile App or Services.
</div><div>Third Party Information Collection. While we do not include any third party advertisements on our Website or in our Services, when you access or use our Websites and Services, or access their content, certain third parties, such as advertisers, analytics companies (e.g. Google Analytics), your mobile device manufacturer or your mobile service provider may use automatic information collection technologies to collect information about you, your computer or your device.  We have no control over these third parties collection and use of your information. The information these third parties collect may be associated with your personal information or your online or mobile activities over time and across different websites, apps and other online services. Such third parties may use this information to provide you with interest-based (behavioral) advertising or other targeted content. We do not control these third parties’ tracking technologies or how they may be used. If you have any questions about an advertisement or other targeted content, you should contact the responsible provider directly.
</div><div>
</div><div><br></div><h3>How We Use Your Information
</h3><div>If you elect to provide us with your information while using the Websites, Mobile App or Services, (for example, by registering on our Websites, Mobile App and Services or e-mailing our Marketing Team.,) we may provide you with church and service related announcements concerning Christ Fellowship or contact you regarding your requests.  For example, all registered users receive a welcome e-mail to confirm their registration.
</div><div>We may also use information that we collect about you or that you provide to us, including any Personal Information to:  (i) provide you with the Websites, Mobile App and Services and their contents, and any other information, materials or services that you request from us; (ii) fulfill any other purpose for which you provide it; (iii) give you notices about your Christ Fellowship Account; (iv) carry out our obligations and enforce our rights and (v) notify you when updates are available, and of changes to any materials or services we offer or provide through the Websites and Services. In addition, your personal contact information may be shared with Church staff and approved volunteers for internal Church purposes.
</div><div>Your general contact information (for example, name, address, and phone number) and other optional information you may choose to provide (for example, email address, photo, and so forth) may be shared with Christ Fellowship staff and volunteers for internal Church purposes.  Some of your information (Such as Groups information, meeting times, etc.) may also be viewable on a limited and restricted basis on our Websites &amp; Services, but only if you opt in to share it. You may opt out of sharing information or limit the optional information you share by modifying your profile settings on our Websites, Mobile App and Services when available.
</div><div>The usage information we collect helps us improve our Websites, Mobile App and Services and deliver a better and more personalized experience by enabling us to estimate our audience size and usage patterns, store information about your preferences, customize our Websites, Mobile App and Services according to your individual interests, speed up your searches, and recognize you when you use the Websites, Mobile App or Services.
</div><div>We use information we collect about your location to customize your online experience to your current location, including providing you with easier access to information about the Christ Fellowship campus closest to you.
</div><div>Disclosure of Your Information. We may disclose Personal Information to, among others, our affiliates, partners, contractors or trusted business providers, who either perform services on our behalf or assist Christ Fellowship.  Examples include credit card processing companies and web hosting companies.   We may transfer Personal Information to any Christ Fellowship-affiliated or unaffiliated church entity to accomplish church purposes, but in doing so, we’ll make sure that your information is treated in compliance with our privacy policy.
</div><div>We also may share information you provide in combination with information from other users with third parties on an aggregate basis (“Aggregate Data”).  Aggregate Data does not contain any information which can be used to identify or contact you.  We will never provide your Personal Information to third parties for their use in marketing their products or services to you without your consent.
</div><div>We will not intentionally share your Personal Information with third parties, except to:
</div><div>(a) interact with our affiliates, partners, contractors or trusted business providers with whom we have obligations of confidentiality with respect to your Personal Information;
</div><div>(b) comply with a valid legal inquiry or process such as a search warrant, subpoena, statute, court order or government request;
</div><div>(c) protect a physical or property threat to you, to others or to the Websites and Services;
</div><div>(d) respond to a breach or attempted breach of the security of our Websites and Services;
</div><div>(e) defend or assert our legal rights;
</div><div>(f) enforce our Terms of Use.
</div><div>Your Choices About Our Collection, Use and Disclosure of Your Information. We strive to provide you with choices regarding the personal information you provide to us.
</div><div>You may choose to not provide us with information requested in your profile.
</div><div>You may opt-out of receiving future marketing communications from us by clicking the “unsubscribe” link at the bottom of any marketing e-mail communication you receive from us or by contacting our Marketing Team and requesting to be unsubscribed.
</div><div>You may also set your browser to refuse all or some browser cookies, or to alert you when cookies are being sent.</div><div><br></div><div>
</div><div>
</div><h3>Third Party Links
</h3><div>Our Websites, Mobile App and Services may contain links to or from other third-party websites.  Please be aware that we are not responsible for the privacy practices of these other websites.  This Privacy Policy applies only to the information we collect on our Websites and Services.  We encourage you to read the privacy policies of other Websites, Mobile App and Services you link to or access through our Websites or otherwise visit.
</div><div>
</div><div>Individuals Under the Age of 13
</div><div>The Websites, Mobile App and Services are not intended for children under 13 years of age, and we do not knowingly collect personal information from children under 13. If we learn we have collected or received personal information from a child under 13 without verification of parental consent, we will delete that information. If you believe we might have any information from or about a child under 13, please contact us at hello@cftoday.org</div><div><br></div><div>
</div><div>
</div><h3>Updating Your Information
</h3><div>You can review and change your personal information by signing into your Christ Fellowship Account and visiting your profile.  You may also review, change and correct your Personal Information, or request that we deactivate your Christ Fellowship Account, by contacting our Marketing Team. Please understand that should you opt to deactivate your account; we will act in good faith to delete your user generated content. However, we are required by law or regulation to maintain information concerning you, we will maintain this information pursuant to our then-current document retention policies. Examples of information that may be retained include the history of donations you made to us.</div><div><br></div><div>
</div><div>
</div><h3>Your California Privacy Rights
</h3><div>Under California Civil Code Section 1798.83, California residents who use our Websites, Mobile App or Services may request certain information regarding our disclosure of personal information to third parties for direct marketing purposes.  To make such a request, please send us an email at hello@cftoday.org or write us at Communications Team, 5343 Northlake Blvd., Palm Beach Gardens, FL 33418.
</div><div>
</div><div>Security
</div><div>We implement reasonable measures designed to protect your personal information from accidental loss or unauthorized access, use, alteration or disclosure.  However, no data transmission or storage system can be guaranteed to be 100% secure.  We cannot warrant the security of your information, and your use of our Websites, Mobile App and Services is at your own risk.  Remember, the safety and security of your information also depends on you.  We urge you to protect your user information and password and to be careful about giving out information in public areas of the Websites, Mobile App or Services, which may be viewed by other users of the Websites, Mobile App or Services.</div><div><br></div><div>
</div><div>
</div><h3>Changes to this Policy
</h3><div>This Privacy Policy may change from time to time and your continued use our Websites, Mobile App or Services after we make changes is deemed to be acceptance of those changes. So, please check this policy periodically for updates.  It is our policy to post any changes we make to our Privacy Policy on this page.  If we make material changes to how we treat our users’ Personal Information, we will notify you by e-mail (if you have an email address on record with us) and through a notice on the Websites home pages.  The date the Privacy Policy was last revised is identified at the top of the page.
</div><div>
</div><div>Disputes; Mediation; Arbitration; Waiver of Class Action
</div><div>This Privacy Policy is subject to our Terms of Use, including Section 9 of our Terms of Use, which includes mediation and binding arbitration (unless you opt out of arbitration within 60 days of the earlier of your first use of the Websites, Mobile App or Services or registration with the Websites, Mobile App or Services) and a waiver of certain class action rights.  Please carefully review these terms, as well as the rest of the Terms of Use before using our Websites, Mobile App or Services.</div><div><br></div><div>
</div><div>
</div><h3>Let Us Know How We Are Doing
</h3><div>We have taken great measures to ensure that your visit to our Websites, Mobile App and Services are a positive experience and that your privacy is constantly respected.  If you have any questions, comments, or concerns about our privacy practices, please let us know.</div><div>
</div><div><br><b>Marketing Team
</b></div><div>Christ Fellowship Church</div></div><div class=""></div><div class=""></div></div>`;

export default function PrivacyPolicy() {
  return (
    <Layout title="Privacy Policy">
      <Box mb="base" textAlign="center">
        <Box as="h1">Privacy Policy</Box>
        <Box as="i">Last Updated: September 12th 2019</Box>
      </Box>
      <Box>{htmlToReactParser.parse(policy)}</Box>
    </Layout>
  );
}
