name: Weekly PR
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if dev branch exists
        run: |
          if [[ ! -d "dev" ]]; then
            echo "dev branch does not exist"
            echo "Creating dev branch"
            git checkout -b dev
          fi
      - id: template
        uses: chuhlomin/render-template@v1.4
        with:
          template: .github/pull-request-template.md
      - name: Create PR
      - uses: peter-evans/create-pull-request@v1
        with:
          branch: 'dev'
          base: 'master'
          title: 'Weekly PR - `r format(Sys.Date(), "%d %B %Y")`'
          body: ${{ steps.template.outputs.result }}
