name: Deploy

on:
  push:
    branches: [main]
  ? workflow_dispatch

jobs:
  bump-version:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1

      - name: 'cat package.json'
        run: cat ./package.json

      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          skip-tag:  'true'

      - name: 'cat package.json'
        run: cat ./package.json